name: responsive_notebook_background_example
description: Demonstrates how to use responsive_notebook_background.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  responsive_notebook_background:
    path: ../
  flutter_lorem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: 0.12.0
  dart_code_linter: ^3.0.0

flutter:
  uses-material-design: true
